### PR TITLE
Migrate from Travis-CI to Github Actions

### PR DESCRIPTION
**Pull request by liry**
Since Maven is not supported by Coveralls GH Action,
we also need to migrate coverage to Codecov.

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by sadam21** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-http-client-merge-compliance-check/34/ : SUCCESS in 26s
- https://checklist.intgdc.com/job/compliance/job/gooddata-http-client-fossa-scanning-zuul-el7/23/ : FAILURE in 1m 35s (non-voting)

**Pull request merged**
