### PR TITLE
Update links in README

### PR DESCRIPTION
**Pull request by liry**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by liry** [comment]
retest this please

**Comment by liry** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-http-client-merge-compliance-check/1/ : SUCCESS in 37s

**Pull request merged**
